import figureSequences from '@/content/sections/figure-sequences/questions.json'
import mathematicalEquations from '@/content/sections/mathematical-equations/questions.json'
import latinSquares from '@/content/sections/latin-squares/questions.json'

import type { SectionId } from '@/lib/sections'
import type { Difficulty, Question } from '@/lib/types/question'

/**
 * Single lookup point for section content.
 *
 * The banks are generated by `scripts/generate` and validated by
 * `scripts/verify-bank.mjs`, which is where the real guarantees come from — the
 * cast here just gives the app the narrow types JSON import can't infer.
 */
const BANKS: Record<SectionId, Question[]> = {
  'figure-sequences': figureSequences as unknown as Question[],
  'mathematical-equations': mathematicalEquations as unknown as Question[],
  'latin-squares': latinSquares as unknown as Question[],
}

export function getQuestions(sectionId: SectionId): Question[] {
  return BANKS[sectionId]
}

export function getQuestion(sectionId: SectionId, id: string): Question | undefined {
  return BANKS[sectionId].find((q) => q.id === id)
}

export function countByDifficulty(sectionId: SectionId): Record<Difficulty, number> {
  const counts: Record<Difficulty, number> = { low: 0, medium: 0, high: 0 }
  for (const q of BANKS[sectionId]) counts[q.difficulty] += 1
  return counts
}

export function getBankSize(sectionId: SectionId): number {
  return BANKS[sectionId].length
}
