import figureSequences from '@/content/sections/figure-sequences/questions.json'
import mathematicalEquations from '@/content/sections/mathematical-equations/questions.json'
import latinSquares from '@/content/sections/latin-squares/questions.json'

import { learn as figureLearn } from '@/content/sections/figure-sequences/learn'
import { learn as mathLearn } from '@/content/sections/mathematical-equations/learn'
import { learn as latinLearn } from '@/content/sections/latin-squares/learn'

import { tips as figureTips } from '@/content/sections/figure-sequences/tips'
import { tips as mathTips } from '@/content/sections/mathematical-equations/tips'
import { tips as latinTips } from '@/content/sections/latin-squares/tips'

import type { SectionId } from '@/lib/sections'
import type { LearnPage, TipsPage } from '@/lib/types/content'
import type { Difficulty, Question } from '@/lib/types/question'

/**
 * Single lookup point for section content.
 *
 * The banks are generated by `scripts/generate` and validated by
 * `scripts/verify-bank.mjs`, which is where the real guarantees come from — the
 * cast here just gives the app the narrow types JSON import can't infer.
 */
const BANKS: Record<SectionId, Question[]> = {
  'figure-sequences': figureSequences as unknown as Question[],
  'mathematical-equations': mathematicalEquations as unknown as Question[],
  'latin-squares': latinSquares as unknown as Question[],
}

const LEARN: Record<SectionId, LearnPage> = {
  'figure-sequences': figureLearn,
  'mathematical-equations': mathLearn,
  'latin-squares': latinLearn,
}

const TIPS: Record<SectionId, TipsPage> = {
  'figure-sequences': figureTips,
  'mathematical-equations': mathTips,
  'latin-squares': latinTips,
}

export function getLearn(sectionId: SectionId): LearnPage {
  return LEARN[sectionId]
}

export function getTips(sectionId: SectionId): TipsPage {
  return TIPS[sectionId]
}

export function getQuestions(sectionId: SectionId): Question[] {
  return BANKS[sectionId]
}

export function getQuestion(sectionId: SectionId, id: string): Question | undefined {
  return BANKS[sectionId].find((q) => q.id === id)
}

export function countByDifficulty(sectionId: SectionId): Record<Difficulty, number> {
  const counts: Record<Difficulty, number> = { low: 0, medium: 0, high: 0 }
  for (const q of BANKS[sectionId]) counts[q.difficulty] += 1
  return counts
}

export function getBankSize(sectionId: SectionId): number {
  return BANKS[sectionId].length
}
