import type { SectionId } from '@/lib/sections'
import type { Difficulty, Selection } from '@/lib/types/question'
import type { PracticeMode } from '@/lib/types/progress'

/**
 * The database as the client sees it.
 *
 * Hand-written rather than generated by the Supabase CLI, because generating it
 * would require a live project to introspect and this repository has to build
 * without one. It mirrors `supabase/migrations/*.sql` exactly; change one and
 * change the other.
 */

export type ExposureContext = 'practice' | 'diagnostic' | 'mock'
export type SessionStatus = 'in_progress' | 'completed' | 'expired' | 'abandoned'
export type SessionPhase = 'brief' | 'running' | 'break' | 'done'

export type AttemptRow = {
  id: string
  user_id: string
  question_id: string
  section: SectionId
  difficulty: Difficulty
  mode: PracticeMode
  selection: Selection
  is_correct: boolean
  hints_used: number
  duration_ms: number | null
  session_id: string | null
  attempted_at: string
  created_at: string
}

/** The questions a session was built from, frozen so a resume is the same test. */
export type SessionStageRow = {
  sectionId: SectionId
  label: string
  unitNoun: string
  questionIds: string[]
}

export type SessionRow = {
  id: string
  user_id: string
  mode: PracticeMode
  sections: SectionId[]
  status: SessionStatus
  stages: SessionStageRow[]
  stage_index: number
  current_index: number
  answers: Record<string, Selection>
  hints_used: Record<string, number>
  phase: SessionPhase
  started_at: string
  stage_ends_at: string | null
  completed_at: string | null
  timed_out: boolean
  duration_ms: number | null
  total: number | null
  answered: number | null
  correct: number | null
  updated_at: string
}

export type ExposureRow = {
  user_id: string
  question_id: string
  context: ExposureContext
  section: SectionId
  times_seen: number
  first_seen_at: string
  last_seen_at: string
}

export type UserStateRow = {
  user_id: string
  milestones: Record<string, boolean>
  key_dates: { id: string; label: string; date: string }[]
  updated_at: string
}

export type ProfileRow = {
  id: string
  display_name: string | null
  avatar_url: string | null
  created_at: string
  updated_at: string
}

type Table<Row, Insert = Row> = {
  Row: Row
  Insert: Insert
  Update: Partial<Insert>
  Relationships: []
}

/** `user_id` is omitted on insert: the column defaults to `auth.uid()`. */
type Owned<Row> = Omit<Row, 'user_id'> & { user_id?: string }

export type Database = {
  public: {
    Tables: {
      profiles: Table<ProfileRow, Partial<ProfileRow> & { id: string }>
      attempts: Table<AttemptRow, Owned<Omit<AttemptRow, 'created_at'>> & { created_at?: string }>
      sessions: Table<SessionRow, Owned<Partial<SessionRow>> & { id: string; mode: PracticeMode }>
      question_exposure: Table<
        ExposureRow,
        Owned<Omit<ExposureRow, 'first_seen_at' | 'last_seen_at'>> & {
          first_seen_at?: string
          last_seen_at?: string
        }
      >
      user_state: Table<UserStateRow, Owned<Partial<UserStateRow>>>
    }
    Views: Record<never, never>
    Functions: Record<never, never>
    Enums: Record<never, never>
    CompositeTypes: Record<never, never>
  }
}
